### PR TITLE
Scan allows ParamSpace as input

### PR DESCRIPTION
**Pull request by mikkokotila**
## You want to make a PR to Talos

Thanks so much :) First, please take a moment to carefully check through
the below items:

#### Sanity

- [x] I'm aware of the implications of the proposed changes
- [x] Code is [PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] I'm making the PR to `master`
- [x] I've changed the version in `setup.py` based on [Semantic Versioning](https://semver.org/)

#### Docs

- [ ] [Docs](https://autonomio.github.io/talos) are updated
- [ ] [Docs](https://autonomio.github.io/talos) version is correct on (index.html and _coverpage.md)

#### Tests

- [x] Changes have gone through actual use testing
- [x] All local tests have passed (run ./test.sh in /talos)
- [x] Tests have been updated to reflect the changes

<hr>

### CODE REVIEW

**Comment by abhijithneilabraham** [comment]
Hi @mikkokotila 

I tried the below script for testing the scan input as Paramspace object.

```
import talos
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from talos import Scan
from talos.parameters.DistributeParamSpace import DistributeParamSpace

dataset = loadtxt(
    "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")

x = dataset[:, 0:8]
y = dataset[:, 8]

def diabetes(x_train, y_train, x_val, y_val, params):

    # replace the hyperparameter inputs with references to params dictionary
    model = Sequential()
    print("-----------------------", params)
    model.add(Dense(params['first_neuron'], input_dim=8,
              activation=params['activation']))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy',
                  optimizer='adam', metrics=['accuracy'])

    # make sure history object is returned by model.fit()
    out = model.fit(x=x,
                    y=y,
                    validation_data=[x_val, y_val],
                    epochs=4,
                    batch_size=params['batch_size'],
                    verbose=0)

    # modify the output model
    return out, model


p = {'first_neuron': [12, 24, 48],
     'activation': ['relu', 'elu'], 
     'batch_size': [10, 20, 40]}

exp_name="diabetes_exp"



dp = DistributeParamSpace(params=p,param_keys=p.keys(),machines=2)
split_params=dp._split_param_space()[1] #taking 1st index with split param space object
print(split_params)
t = Scan(x=x, y=y, params=split_params, model=diabetes, experiment_name=exp_name,
                        )
```

I am getting the following error:

```
    t = Scan(x=x, y=y, params=split_params, model=diabetes, experiment_name=exp_name,
  File "/Users/abhigith.abraham/opt/anaconda3/envs/py/lib/python3.6/site-packages/talos-1.1.1-py3.6.egg/talos/scan/Scan.py", line 196, in __init__
    scan_run(self)
  File "/Users/abhigith.abraham/opt/anaconda3/envs/py/lib/python3.6/site-packages/talos-1.1.1-py3.6.egg/talos/scan/scan_run.py", line 26, in scan_run
    self = scan_round(self)
  File "/Users/abhigith.abraham/opt/anaconda3/envs/py/lib/python3.6/site-packages/talos-1.1.1-py3.6.egg/talos/scan/scan_round.py", line 19, in scan_round
    self.model_history, self.round_model = ingest_model(self)
  File "/Users/abhigith.abraham/opt/anaconda3/envs/py/lib/python3.6/site-packages/talos-1.1.1-py3.6.egg/talos/model/ingest_model.py", line 10, in ingest_model
    self.round_params)
  File "newtemp.py", line 20, in diabetes
    model.add(Dense(params['first_neuron'], input_dim=8,
KeyError: 'first_neuron'
```

Also when I try printing the params inside the `diabetes` function , it shows the params is empty. Can you address this in your PR?

**Comment by abhijithneilabraham** [comment]
Fixed all issues and ran tests.

**Comment by mikkokotila** [comment]
> Fixed all issues and ran tests.

Sorry, what do you mean? Fixed issues where?

**Comment by abhijithneilabraham** [comment]
@mikkokotila , sorry I put in the wrong comment. I meant, I ran all the tests and tested locally. It is working. I also updated with a commit involving a docs change for Scan.md .

**Pull request merged**
