### PR TITLE
Modify ParamGrid to compute only the part of the grid in the selected downsample

### PR DESCRIPTION
**Pull request by JohanMollevik**
There are some outstanding issues regarding shuffle and stratified that needs to be tested, otherwise seems to work. More testing is of cource prudent

### CODE REVIEW

**Comment by mikkokotila** [comment]
Thanks for PR. I will dig in once the test finishes. I'll ask questions / clarifications here as per needed.

**Comment by mikkokotila** [comment]
To be frank, I don't always do it myself, but generally speaking one can save much time by running`test_script.py` locally before commit/push/pr.

**Comment by JohanMollevik** [comment]
I will check why it failed, but based on the test output I think it is related to my question regarding how stratified is supposed to work.

Did not know of the test suit, will start to use that

**Comment by JohanMollevik** [comment]
Looking at the tests I see two issues
1) the warning regarding matplotlib.use(), this seems related to order of imports, when I changed the import order in my ovn code to import chances before talos it dissapeared, same thing happened in the test suit
2) the error in test_scan_cancer_loss_reduction is related to my question about stratified, how is it supposed to work?

**Comment by mikkokotila** [comment]
Stratified is not fixed as easily as I thought in my comment in the corresponding issue. I've removed it now and will deal with it later separately. But note that I will leave everything else in place with adding it shortly back in mind. 

Running tests just passed and will commit to daily-dev now. That should re-initiate the test automatically.

**Comment by JohanMollevik** [comment]
Great

**Comment by mikkokotila** [comment]
I think you have to change the matplotlib references to the way it was originally, as otherwise the tests can't pass.

**Comment by JohanMollevik** [comment]
I have not referenced matplotlib in this code (not as far as I know), for me locally it started apearing once I updated 'chances' from git.

**Comment by mikkokotila** [comment]
Ah yea, I just realized that. Strange thing here is that chances pypi have not been changed since 9th of February (which is the version Travis will install). I need to find out what's going on.

**Comment by mikkokotila** [comment]
Ah ok, that's just Travis acting up. It does happen occasionally. You can see the details for python3 versions to get the actual error: 

```
Traceback (most recent call last):
  File "./test_script.py", line 12, in <module>
    TestCancer().test_scan_cancer_metric_reduction()
  File "/home/travis/build/autonomio/talos/test/core_tests/test_scan.py", line 111, in test_scan_cancer_metric_reduction
    reduction_interval=2)
  File "/home/travis/build/autonomio/talos/talos/scan/Scan.py", line 165, in __init__
    self._null = self.runtime()
  File "/home/travis/build/autonomio/talos/talos/scan/Scan.py", line 169, in runtime
    self = scan_prepare(self)
  File "/home/travis/build/autonomio/talos/talos/scan/scan_prepare.py", line 42, in scan_prepare
    self.paramgrid_object = ParamGrid(self)
  File "/home/travis/build/autonomio/talos/talos/parameters/ParamGrid.py", line 40, in __init__
    out = sample_reducer(self,final_grid_size,virtual_grid_size)
  File "/home/travis/build/autonomio/talos/talos/reducers/sample_reducer.py", line 31, in sample_reducer
    n = int(len(self.param_grid) * self.main_self.grid_downsample)
AttributeError: 'ParamGrid' object has no attribute 'param_grid'
The command "coverage run --source=talos ./test_script.py" exited with 1.
```

With the proposed changes the self that is input to sample_reducer no longer has param_grid, which is because the it is the ParamGrid object that is being passed, not the actual Scan self. Looks like that.

**Comment by JohanMollevik** [comment]
wierd in my commit I remove the line n = int(len(self.param_grid) * self.main_self.grid_downsample) and looking at the git history shows that but the line is ther in later commits ... my git fuu is weak will look into this

**Comment by mikkokotila** [comment]
That's my bad. I made some changes to the file as I saw there was something commented out from the past. I should have been more careful. But as I see `self.param_grid` is called immediately after in that file in any case, so would that not throw the same error?

**Comment by JohanMollevik** [comment]
If you are asking about shuffle, now we are back to my question 1 in the original pull request comment

**Comment by mikkokotila** [comment]
But I think the issue is that the proposed change calls sample_reducer before self.param_grid is created. That is not possible: 
```
        # select premutations according to downsample
        if final_grid_size < virtual_grid_size:
            out = sample_reducer(self,final_grid_size,virtual_grid_size)
        else:
            out = range(0,final_grid_size)

        # build the parameter permutation grid
        self.param_grid = self._param_grid(ls,out)

```

**Comment by mikkokotila** [comment]
> If you are asking about shuffle, now we are back to my question 1 in the original pull request comment

Also `r = chances.Randomizer(len(self.param_grid), n)` is dependent on `self.param_grid`.

**Comment by JohanMollevik** [comment]
Why? The entire idea is to make that possible, depending on what kind of data dependencies exists it works except shuffle. Would it be enough to shuffle in ParamGrid after the grid has been created?

**Comment by JohanMollevik** [comment]
In my commit the r = chances.Randomizer(len(self.param_grid), n) was changed to take the length as a parameter to the function

**Comment by mikkokotila** [comment]
Ok, I think I understand now. So basically we have to move:

```
    # initialize with random shuffle if needed
    if self.main_self.shuffle:
        random.shuffle(self.param_grid)
```
...to ParamGrid.py and that should do it. 

Unfortunately conflict resolution is the worst thing about github and should be avoided as much as possible, so I will take a moment to think how to do this. Also the risk is that we end up with daily-dev which does not pass tests and is not properly tested so have to be careful now.

**Comment by JohanMollevik** [comment]
Yes that should do it

**Comment by mikkokotila** [comment]
Ok good. I think that if you change ParamGrid in push again, and I do the changes to sample_reduce we will have no conflict (fingers cross). 

I think if you can change: 

```
# build the parameter permutation grid
self.param_grid = self._param_grid(ls,out)

# create a index for logging purpose
self.param_log = list(range(len(self.param_grid)))
```
to:

```
# build the parameter permutation grid
self.param_grid = self._param_grid(ls,out)

# initialize with random shuffle if needed
if self.main_self.shuffle:
    random.shuffle(self.param_grid)

# create a index for logging purpose
self.param_log = list(range(len(self.param_grid)))
```

**Comment by JohanMollevik** [comment]
Trying that

**Comment by mikkokotila** [comment]
Ok, looks like we're past it. Now there is an issue with reducer. 

Maybe check the files in the proposed change (as there have been some back and forth) [here](https://github.com/autonomio/talos/blob/ea0a727c431f4239b0cbdde978c86d7684d7f5ea/talos/parameters/ParamGrid.py), [here](https://github.com/autonomio/talos/blob/ea0a727c431f4239b0cbdde978c86d7684d7f5ea/talos/reducers/sample_reducer.py), and [here](https://github.com/autonomio/talos/blob/ea0a727c431f4239b0cbdde978c86d7684d7f5ea/talos/scan/scan_run.py) before other troubleshooting just to make sure that everything is now as you had planned it.

**Comment by mikkokotila** [comment]
```
  File "./test_script.py", line 13, in <module>
    TestCancer().test_scan_cancer_loss_reduction()
  File "/home/travis/build/autonomio/talos/test/core_tests/test_scan.py", line 122, in test_scan_cancer_loss_reduction
    reduction_interval=2)
  File "/home/travis/build/autonomio/talos/talos/scan/Scan.py", line 165, in __init__
    self._null = self.runtime()
  File "/home/travis/build/autonomio/talos/talos/scan/Scan.py", line 170, in runtime
    self = scan_run(self)
  File "/home/travis/build/autonomio/talos/talos/scan/scan_run.py", line 18, in scan_run
    self = scan_round(self)
  File "/home/travis/build/autonomio/talos/talos/scan/scan_round.py", line 65, in scan_round
    self = reduce_run(self)
  File "/home/travis/build/autonomio/talos/talos/reducers/reduce_run.py", line 20, in reduce_run
    self = correlation(self)
  File "/home/travis/build/autonomio/talos/talos/reducers/correlation.py", line 21, in correlation
    out = out.index[-1], out[-1]
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3957, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
The command "coverage run --source=talos ./test_script.py" exited with 1.
```

**Comment by mikkokotila** [comment]
BOOM! 

I took some time to familiarize with the code and tested some parts of it separately.  It seems to make sense, though I did not understand everything exactly. Given we are on daily-dev which is supposed to be experimental, and tests have passed, I'm going to merge and then start doing some more robust test locally. So far so good. 

Really great contribution! :)

**Comment by mikkokotila** [comment]
By the way, the mystic issue with the correlation reducer, I found what it was and it's fixed now as well. It had to do with the `correlation.py` code. 

This contribution was very helpful also in the way that it allowed cleaning up related codes in multiple meaningful ways :)

**Comment by JohanMollevik** [comment]
Thanks for the praise

The latest code looks good to me to, there is one small beauty issue

the line

 n = int(max_value * self.main_self.grid_downsample)

in sample_reducer is redundant, the value computed 'n' is the same value that is passed in as length

Otherwise I think we managed to merge :)

**Pull request merged**
