### PR TITLE
Tidied up hidden_layers

### PR DESCRIPTION
**Pull request by JanPokorny**
Hi, I have tidied up the function hidden_layers:

- fixed the inconsistency with required parameters
- removed the ugly, slow, and confusing-stacktrace-producing misuse of try/catch
- small PEP8 fixes

The test coverage should stay the same, as the functionality didn't change.

### CODE REVIEW

**Comment by JanPokorny** [comment]
@coveralls is lying, I haven't touched that line, I just had to split it so PEP 8 passes

**Comment by mikkokotila** [comment]
Thanks but I think there is an issue. 

For the common case where there is no `kernel_initializer` in params dictionary, the proposed: 

`kernel_regularizer=params.get('kernel_regularizer')`

returns nothing. Whereas, the original:

```
    try:	
        kernel_initializer = params['kernel_initializer']	
    except KeyError:	
        kernel_initializer = 'glorot_uniform'
```
...returns `glorot_uniform` ... which is exactly what we want because it's the Keras default setting for the argument. 

If there is a better way to do this (ideally have Talos automatically use Keras default setting if not set in the params dictionary), then that would be great.

**Comment by JanPokorny** [comment]
@mikkokotila Hello, you have confused kernel_initializer and kernel_regularizer! Take a second look, my code does precisely what the old did. Note that .get(...) returns the value of its second argument when the value is not present in the dictionary (or None if you don't specify it).

**Comment by mikkokotila** [comment]
Ah, got it, that's right I was confused indeed 👍 

Ok I understand now, in that case this is great. Can you make the PR to `daily-dev` as that's the place for PR merges. It will make its way from there to `dev` and eventually `master` (and finally at some point to pypi i.e. `production`).

**Comment by JanPokorny** [comment]
@mikkokotila I was following CONTRIBUTING.md, you should update it then!

**Comment by JanPokorny** [comment]
@mikkokotila Also unsure why Travis is broken, it was broken even before I changed the destination branch. Looks like some problem with pickling. I think that this PR didn't cause it as it essentially doesn't change any behavior. Can you check that please?

**Comment by mikkokotila** [comment]
Sorry for taking ages with this. The big push to move from 0.5 to 0.6.3 took a couple of months in total, and this came a couple of weeks into that. Thanks again :)

**Pull request merged**
