### PR TITLE
Fixed small typo

### PR DESCRIPTION
**Pull request by roohat**
Fixed small typo

It's not that much of an issue but this could of easily prevented by having some Git typo hook to decline push/merge requests with typo in it. (e.g., https://github.com/intgr/topy)

### CODE REVIEW

**Comment by roohat** [comment]
BTW, since talos uses Travis CI for CI there is way to add spelling integration as Travis addon. For integrate instructions: https://blog.eleven-labs.com/en/how-to-check-the-spelling-of-your-docs-from-travis-ci/

**Comment by roohat** [comment]
I should add a CI integration to myself. Accidentally closed the merge request 😅

**Comment by x94carbone** [comment]
Hah! Thank you for catching this. I see no reason why we shouldn't merge this obviously, but I always wait for @mikkokotila's approval.

Wonder if it'll pass Travis...

**Comment by mikkokotila** [comment]
Very good idea on adding the spelling hook for Travis! :) Will merge this now, but if you want to make a new one with the spelling hook, that will be great :)

**Pull request merged**
