### PR TITLE
Add ability to filter out unwanted premutations

### PR DESCRIPTION
**Pull request by JohanMollevik**
I propose to fix https://github.com/autonomio/talos/issues/223 by this pull request

The code is used like

    talos.Scan(
        ...
        ,premutation_filter=lambda p: p['hidden_layers']<3 or p['first_neuron']<10)

I have tested locally but not added any tests

### CODE REVIEW

**Comment by JohanMollevik** [comment]
What is your thoughts on this? Is the code acceptable as is? Regarding the tests, am I right in thinking that the issue it complains about is coverage?

**Comment by mikkokotila** [comment]
> What is your thoughts on this? Is the code acceptable as is? Regarding the tests, am I right in thinking that the issue it complains about is coverage?

You are right,  it is because of coverage. So ideally, because we are below 100%, the coverage should remain same or rise a little (i.e. some new test comes as a byproduct). For adding a new feature, it's definitely good idea to add a test for it. Could you do it, and I will review the changes in the meantime.

**Comment by mikkokotila** [comment]
Related with testing, when creating new tests, it's also a good idea to check the [coverage report](https://coveralls.io/builds/21923638) and use other parameters in Scan() (or which ever command is invoked) which do not already have coverage (or have few hits).

**Comment by JohanMollevik** [comment]
Ok, I will create a test for this.

**Comment by mikkokotila** [comment]
Great :)  

Also check out the pep8speaks report above for flags on pep8 violations. I've followed an approach where otherwise its strict pep8, but if lines are barely longer than the allowed 80, then let it be. If it's longer, then split as the first-line measure split the code into several commands, and if that is not possible, only then use `\`.

**Comment by mikkokotila** [comment]
By the way, if I understood correctly, I think that this feature will be very useful as part of "reducers". As far as I collect, we could have a reducer say "drop anything with first_neuron > 5 where also batch_size < 128". Is it correct?

**Comment by JohanMollevik** [comment]
Yes, that is exactly the use case for it

**Comment by mikkokotila** [comment]
It [looks like](https://travis-ci.org/autonomio/talos/jobs/500249878) the test takes a long time.

**Comment by JohanMollevik** [comment]
Right that is why I do not see any test results, I will fix that

**Comment by JohanMollevik** [comment]
Is there any way to get it to report any ramaining pep8 errors? The list at the top is a bit out of date

**Comment by JohanMollevik** [comment]
Are there any way to kill the running tests to let the fixed one run?

**Comment by mikkokotila** [comment]
It's killed. I could do it when I'm logged into Travis.

**Comment by JohanMollevik** [comment]
One long running test still running? Can you kill that and restart the current one?

**Comment by mikkokotila** [comment]
Done. For future reference, it was not first apparent where to do it (it was hidden). Have to click through the PR, and only after then it became visible. On the top view it appeared as if nothing was running.

**Comment by mikkokotila** [comment]
I've cancelled the build because it wanted to go through 16000 permutations (as opposed to 22000 before).

**Comment by mikkokotila** [comment]
I think this will be good: 

```
    def test_scan_iris_3(self):
        print("Running Iris dataset test 2...")
        Scan(self.x, self.y, params=p3, dataset_name='testing',
             experiment_no='000', model=ta.templates.models.iris,
             premutation_filter=lambda p: p['first_neuron'] * p['hidden_layers'] < 9,
             last_epoch_value=True)
```

This should yield exactly 2 permutations and will be in line with the other tests.

**Comment by JohanMollevik** [comment]
Sorry for all the commits, hopefully this works

**Comment by JohanMollevik** [comment]
Hmm, got another error, should I squash the commits once I get the tests to pass to avoid poluting the commit log when merging

**Comment by mikkokotila** [comment]
No worries, it's fine if you think it's getting close :) 

For future, once you add the test, it's best to run ` test_script.py` locally and once it pass then push. When I'm adding something new, or make change to the mainline code, I usually leave `test_script.py` running like so: 

```
while : 
do
    python test_script.py
done
```

...I might leave it running for an hour or two. But I don't do that for minor changes. Then I just run once locally before push.

Sometimes there are "random" bugs that appear only when certain circumstances are present, so this works towards that end.

**Comment by JohanMollevik** [comment]
I tried to run locally but got errors in the tests where they expected tensorflow to be installed, I'm runing cntk so that prevented me from running the tests.

**Pull request merged**
